apiVersion: apps/v1
kind: Deployment
metadata: 
     name: helloworld
     labels: 
        app: webapp 
spec:
     replicas: 1
     selector:
        matchLabels:
           app: webapp
     template:
        metadata:
           labels:
              app: webapp
        spec:
           containers:
            - name: tomcat
              image: kiran5108/tomcat:tag-version
              ports:
              - containerPort: 8080
              resources:
                limits:
                  cpu: 500m
                requests:
                  cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
    
spec:
  type: NodePort
  selector: 
      app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webapphpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helloworld
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5   
